### PR TITLE
Backwards compatible buffer constructor

### PR DESCRIPTION
**Pull request by omouse**
only needed if we want to allow for Amazon Lambda usage which uses older versions of Node like 4.x and 0.10.x

### CODE REVIEW

**Comment by caco0516** [comment]
Still needing help with this ?

**Comment by omouse** [comment]
@caco0516 yeah I tried a few different methods (but I'm recovering from a cold). You can work with this PR or create a new branch from master.

**Comment by caco0516** [comment]
@omouse Ok I will work on this ...

**Comment by caco0516** [comment]
@omouse Look we got it ... We can use both of constructor just for backward compatibility. What you say ?

**Comment by omouse** [comment]
Yep that makes sense, I didn't think to look at the tests to make sure they're using the right buffer method. I'll resolve the conflicts and it's good to merge. Looks like we can support older versions of node now! Thanks @caco0516 :+1:

**Comment by caco0516** [comment]
@omouse Your welcome !!!

**Pull request merged**
